#!/bin/bash

clear
mkdir animations

echo "*****************************"
echo "*** Script to create MOVs ***"
echo "*****************************"
echo " "

################################
####### MATCH C LINEAR #########
################################
pre_path="./het_matchC_linear"
echo "matchC linear"
#track
echo "  track"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_track_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_track_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_track_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_track_strain_slices.mov"
#no track
echo "  notrack"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/no_track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_notrack_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_notrack_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/no_track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_notrack_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_linear_notrack_strain_slices.mov"

####################################
####### MATCH C NON-LINEAR #########
####################################
pre_path="./het_matchC_nonlinear"
echo "matchC nonlinear"
#track
echo "  track"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_track_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_track_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_track_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_track_strain_slices.mov"
#no track
echo "  notrack"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/no_track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_notrack_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_notrack_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/no_track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_notrack_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_matchC_nonlinear_notrack_strain_slices.mov"

#####################################
####### MISS-MATCH C LINEAR #########
#####################################
pre_path="./het_miss-matchC_linear"
echo "miss-matchC linear"
#track
echo "  track"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_track_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_track_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_track_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_track_strain_slices.mov"
#no track
echo "  notrack"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/no_track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_notrack_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_notrack_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/no_track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_notrack_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_linear_notrack_strain_slices.mov"

#########################################
####### MISS-MATCH C NON-LINEAR #########
#########################################
pre_path="./het_miss-matchC_nonlinear"
echo "miss-matchC nonlinear"
#track
echo "  track"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_track_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_track_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_track_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_track_strain_slices.mov"
#no track
echo "  notrack"
echo "    stress"
echo "      pcolor"
path="$pre_path/_plots/no_track/stress/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_notrack_stress_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/stress/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_notrack_stress_slices.mov"
echo "    strain"
echo "      pcolor"
path="$pre_path/_plots/no_track/strain/pcolor"
convert -delay 5 -loop 0 "$path/*.png" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_notrack_strain_pcolor.mov"
echo "      slices"
path="$pre_path/_plots/no_track/strain/slices"
convert -delay 5 -loop 0 "$path/*.eps" -delay 200 "$path/*0400*" "./animations/het_miss-matchC_nonlinear_notrack_strain_slices.mov"
